# Generated by Django 3.1.7 on 2021-05-06 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0002_auto_20210505_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroommodel',
            options={'ordering': ['is_private', 'name']},
        ),
    ]
