# Generated by Django 3.1.7 on 2021-05-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0003_auto_20210506_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommodel',
            name='name',
            field=models.CharField(help_text='room name', max_length=30, unique=True),
        ),
    ]
