# Generated by Django 3.1.7 on 2021-05-06 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0004_auto_20210506_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroommodel',
            options={'ordering': ['-is_private', 'name']},
        ),
    ]
