# Generated by Django 3.1.7 on 2021-05-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0007_auto_20210506_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessagemodel',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalChatMessageModel',
        ),
    ]
