# Generated by Django 3.1.7 on 2021-05-21 08:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0010_auto_20210517_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessagemodel',
            name='backup_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='chatmessagemodel',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatroommodel'),
        ),
        migrations.AlterField(
            model_name='chatroommodel',
            name='backup_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
