# Generated by Django 3.1.7 on 2021-04-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackerapp", "0027_auto_20210331_1853"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmodel",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
    ]
