# Generated by Django 3.1.7 on 2021-04-06 16:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('trackerapp', '0029_auto_20210401_0835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'ordering': ['creation_date', 'title']},
        ),
    ]
