# Generated by Django 3.1.7 on 2021-04-12 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0032_auto_20210408_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to='uploads/userprofile/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
