# Generated by Django 3.1.7 on 2021-04-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trackerapp', '0034_auto_20210413_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
