# Generated by Django 3.1.7 on 2021-04-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trackerapp', '0036_auto_20210423_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltaskmodel',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
