# Generated by Django 3.1.7 on 2021-04-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0037_auto_20210423_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalattachment',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicaltaskmodel',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='changed_by',
        ),
    ]
