# Generated by Django 3.1.7 on 2021-04-23 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trackerapp', '0038_auto_20210423_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalattachment',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalattachment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicaltaskmodel',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
