# Generated by Django 3.1.7 on 2021-04-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0039_auto_20210423_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'ordering': ['-creation_date', 'title']},
        ),
    ]
