# Generated by Django 3.1.7 on 2021-04-28 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0040_auto_20210427_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'ordering': ['-creation_date']},
        ),
    ]
