# Generated by Django 3.1.7 on 2021-04-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0042_auto_20210428_0601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'ordering': ['-creation_date']},
        ),
    ]
