# Generated by Django 3.1.7 on 2021-05-17 11:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trackerapp', '0044_auto_20210428_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='backup_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='historicalattachment',
            name='backup_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='historicaltaskmodel',
            name='backup_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='message',
            name='backup_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='backup_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
