# Generated by Django 3.1.7 on 2021-05-20 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0045_auto_20210517_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trackerapp.taskmodel'),
        ),
        migrations.AlterField(
            model_name='message',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trackerapp.taskmodel'),
        ),
    ]
