# Generated by Django 3.1.7 on 2021-05-21 08:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trackerapp', '0046_auto_20210520_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='backup_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='attachment_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalattachment',
            name='backup_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='historicaltaskmodel',
            name='backup_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='backup_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_tasks',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
