# Generated by Django 3.1.7 on 2021-05-21 10:40

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trackerapp', '0047_auto_20210521_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalattachment',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicaltaskmodel',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
